In [1]:
import pandas as pd
import numpy as np
from datetime import date
import datetime as date_time
import time

In [2]:
df = pd.read_csv('US_Accidents_Dec21_updated.csv')

In [3]:
df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.865010,-84.048730,0.747,At OH-4/OH-235/Exit 41 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,39.102090,-84.523960,0.055,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,41.062170,-81.535470,0.123,At Dart Ave/Exit 21 - Accident.,...,False,False,False,False,False,False,Night,Night,Day,Day
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,At Mitchell Ave/Exit 6 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845337,A-2845338,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,33.998880,-117.370940,0.543,At Market St - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2845338,A-2845339,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,32.765550,-117.153630,0.338,At Camino Del Rio/Mission Center Rd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2845339,A-2845340,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,33.777400,-117.857270,0.561,At Glassell St/Grand Ave - Accident. in the ri...,...,False,False,False,False,False,False,Day,Day,Day,Day
2845340,A-2845341,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,33.983110,-118.395650,0.772,At CA-90/Marina Fwy/Jefferson Blvd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2845341,A-2845342,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,34.137360,-117.239340,0.537,At Highland Ave/Arden Ave - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [4]:
#dropped 'Turning_Loop', 'Weather_Timestamp', 'Start_Lat','Start_Lng','End_Lat','End_Lng','Airport_Code', 'Side',
#'Number', 'Description', 'ID', 'Country', 'Timezone'
#'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Sunrise_Sunset'
#'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight', 'End_Time'
#'Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Precipitation(in)'

to_drop=['Turning_Loop', 'Weather_Timestamp', 'Start_Lat','Start_Lng','End_Lat','End_Lng','Airport_Code', 'Side', 'Number', 'Description', 'ID', 'Country', 'Timezone', 'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight', 'End_Time', 'Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Precipitation(in)']
df.drop(to_drop, inplace=True, axis=1)

In [5]:
df

,Severity,Start_Time,Distance(mi),Street,City,County,State,Zipcode,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition
0,3,2016-02-08 00:37:08,3.230,Outerbelt E,Dublin,Franklin,OH,43017,42.1,36.1,58.0,29.76,10.0,SW,10.4,Light Rain
1,2,2016-02-08 05:56:20,0.747,I-70 E,Dayton,Montgomery,OH,45424,36.9,NaN,91.0,29.68,10.0,Calm,NaN,Light Rain
2,2,2016-02-08 06:15:39,0.055,I-75 S,Cincinnati,Hamilton,OH,45203,36.0,NaN,97.0,29.70,10.0,Calm,NaN,Overcast
3,2,2016-02-08 06:51:45,0.123,I-77 N,Akron,Summit,OH,44311,39.0,NaN,55.0,29.65,10.0,Calm,NaN,Overcast
4,3,2016-02-08 07:53:43,0.500,I-75 S,Cincinnati,Hamilton,OH,45217,37.0,29.8,93.0,29.69,10.0,WSW,10.4,Light Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845337,2,2019-08-23 18:03:25,0.543,Pomona Fwy E,Riverside,Riverside,CA,92501,86.0,86.0,40.0,28.92,10.0,W,13.0,Fair
2845338,2,2019-08-23 19:11:30,0.338,I-8 W,San Diego,San Diego,CA,92108,70.0,70.0,73.0,29.39,10.0,SW,6.0,Fair
2845339,2,2019-08-23 19:00:21,0.561,Garden Grove Fwy,Orange,Orange,CA,92866,73.0,73.0,64.0,29.74,10.0,SSW,10.0,Partly Cloudy
2845340,2,2019-08-23 19:00:21,0.772,San Diego Fwy S,Culver City,Los Angeles,CA,90230,71.0,71.0,81.0,29.62,10.0,SW,8.0,Fair
2845341,2,2019-08-23 18:52:06,0.537,CA-210 W,Highland,San Bernardino,CA,92346,79.0,79.0,47.0,28.63,7.0,SW,7.0,Fair

In [6]:
df = df.dropna()
df

,Severity,Start_Time,Distance(mi),Street,City,County,State,Zipcode,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition
0,3,2016-02-08 00:37:08,3.230,Outerbelt E,Dublin,Franklin,OH,43017,42.1,36.1,58.0,29.76,10.0,SW,10.4,Light Rain
4,3,2016-02-08 07:53:43,0.500,I-75 S,Cincinnati,Hamilton,OH,45217,37.0,29.8,93.0,29.69,10.0,WSW,10.4,Light Rain
5,2,2016-02-08 08:16:57,1.427,State Route 32,Williamsburg,Clermont,OH,45176,35.6,29.2,100.0,29.66,10.0,WSW,8.1,Overcast
7,2,2016-02-08 11:51:46,0.521,I-71 S,Cleveland,Cuyahoga,OH,44130,33.1,30.0,92.0,29.63,0.5,SW,3.5,Snow
8,2,2016-02-08 14:19:57,0.491,E Hanthorn Rd,Lima,Allen,OH,45806,39.0,31.8,70.0,29.59,10.0,WNW,11.5,Overcast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845337,2,2019-08-23 18:03:25,0.543,Pomona Fwy E,Riverside,Riverside,CA,92501,86.0,86.0,40.0,28.92,10.0,W,13.0,Fair
2845338,2,2019-08-23 19:11:30,0.338,I-8 W,San Diego,San Diego,CA,92108,70.0,70.0,73.0,29.39,10.0,SW,6.0,Fair
2845339,2,2019-08-23 19:00:21,0.561,Garden Grove Fwy,Orange,Orange,CA,92866,73.0,73.0,64.0,29.74,10.0,SSW,10.0,Partly Cloudy
2845340,2,2019-08-23 19:00:21,0.772,San Diego Fwy S,Culver City,Los Angeles,CA,90230,71.0,71.0,81.0,29.62,10.0,SW,8.0,Fair
2845341,2,2019-08-23 18:52:06,0.537,CA-210 W,Highland,San Bernardino,CA,92346,79.0,79.0,47.0,28.63,7.0,SW,7.0,Fair

In [21]:
#change Start_Time to a numerical value instead or a Unix value
#first convert the Start_Time col into dateTime type

#convert column to datetime pandas
df['Start_Time'] = pd.to_datetime(df['Start_Time'])
print(df.Start_Time,"\n")

#Converting it to Unix Timestamp format
#TO_DO, figure out how to apply it to the dataframe
test = df['Start_Time'].astype(np.int64) / 10**9
#print(test, "\n")
test

0         1970-01-01 00:00:01.454891828
4         1970-01-01 00:00:01.454918023
5         1970-01-01 00:00:01.454919417
7         1970-01-01 00:00:01.454932306
8         1970-01-01 00:00:01.454941197
                       ...
2845337   1970-01-01 00:00:01.566583405
2845338   1970-01-01 00:00:01.566587490
2845339   1970-01-01 00:00:01.566586821
2845340   1970-01-01 00:00:01.566586821
2845341   1970-01-01 00:00:01.566586326
Name: Start_Time, Length: 2357693, dtype: datetime64[ns]

C:\Users\Ivan\AppData\Local\Temp\ipykernel_33004\397628961.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Start_Time'] = pd.to_datetime(df['Start_Time'])

0          1.454892
4          1.454918
5          1.454919
7          1.454932
8          1.454941
             ...
2845337    1.566583
2845338    1.566587
2845339    1.566587
2845340    1.566587
2845341    1.566586
Name: Start_Time, Length: 2357693, dtype: float64

In [22]:
df['Start_Time'] = test
df

C:\Users\Ivan\AppData\Local\Temp\ipykernel_33004\563415491.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Start_Time'] = test

,Severity,Start_Time,Distance(mi),Street,City,County,State,Zipcode,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition
0,3,1.454892,3.230,Outerbelt E,Dublin,Franklin,OH,43017,42.1,36.1,58.0,29.76,10.0,SW,10.4,Light Rain
4,3,1.454918,0.500,I-75 S,Cincinnati,Hamilton,OH,45217,37.0,29.8,93.0,29.69,10.0,WSW,10.4,Light Rain
5,2,1.454919,1.427,State Route 32,Williamsburg,Clermont,OH,45176,35.6,29.2,100.0,29.66,10.0,WSW,8.1,Overcast
7,2,1.454932,0.521,I-71 S,Cleveland,Cuyahoga,OH,44130,33.1,30.0,92.0,29.63,0.5,SW,3.5,Snow
8,2,1.454941,0.491,E Hanthorn Rd,Lima,Allen,OH,45806,39.0,31.8,70.0,29.59,10.0,WNW,11.5,Overcast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845337,2,1.566583,0.543,Pomona Fwy E,Riverside,Riverside,CA,92501,86.0,86.0,40.0,28.92,10.0,W,13.0,Fair
2845338,2,1.566587,0.338,I-8 W,San Diego,San Diego,CA,92108,70.0,70.0,73.0,29.39,10.0,SW,6.0,Fair
2845339,2,1.566587,0.561,Garden Grove Fwy,Orange,Orange,CA,92866,73.0,73.0,64.0,29.74,10.0,SSW,10.0,Partly Cloudy
2845340,2,1.566587,0.772,San Diego Fwy S,Culver City,Los Angeles,CA,90230,71.0,71.0,81.0,29.62,10.0,SW,8.0,Fair
2845341,2,1.566586,0.537,CA-210 W,Highland,San Bernardino,CA,92346,79.0,79.0,47.0,28.63,7.0,SW,7.0,Fair

In [23]:
print(df.Weather_Condition.unique())
len(df.Weather_Condition.unique())

['Light Rain' 'Overcast' 'Snow' 'Light Snow' 'Cloudy' 'Mostly Cloudy'
 'Scattered Clouds' 'Clear' 'Partly Cloudy' 'Light Freezing Drizzle'
 'Light Drizzle' 'Haze' 'Rain' 'Fair' 'Fog' 'Patches of Fog'
 'Light Freezing Fog' 'Light Freezing Rain' 'Mist' 'Blowing Snow'
 'Heavy Snow' 'Snow Grains' 'Light Fog' 'Drizzle' 'Thunderstorms and Rain'
 'Heavy Rain' 'Light Ice Pellets' 'Thunder' 'Thunder in the Vicinity'
 'Fair / Windy' 'Light Rain with Thunder' 'Heavy Thunderstorms and Snow'
 'Light Snow Showers' 'Cloudy / Windy' 'Heavy Drizzle' 'Ice Pellets'
 'N/A Precipitation' 'Light Thunderstorms and Rain'
 'Light Thunderstorms and Snow' 'T-Storm' 'Rain / Windy' 'Wintry Mix'
 'Heavy Thunderstorms and Rain' 'Smoke' 'Shallow Fog'
 'Partly Cloudy / Windy' 'Heavy T-Storm' 'Light Rain / Windy'
 'Mostly Cloudy / Windy' 'Blowing Dust / Windy' 'Blowing Dust'
 'Freezing Rain / Windy' 'Small Hail' 'Wintry Mix / Windy'
 'Light Snow / Windy' 'Heavy Ice Pellets' 'Thunderstorm'
 'Heavy Snow / Windy' 'Heavy Rain / Windy' 'Heavy T-Storm / Windy'
 'Fog / Windy' 'Light Rain Showers' 'Showers in the Vicinity'
 'Thunder / Windy' 'Snow / Windy' 'Haze / Windy' 'Light Snow and Sleet'
 'T-Storm / Windy' 'Sand / Dust Whirlwinds' 'Light Snow with Thunder'
 'Rain Shower' 'Blowing Snow / Windy' 'Light Rain Shower' 'Snow and Sleet'
 'Drizzle and Fog' 'Light Sleet' 'Drizzle / Windy' 'Light Snow Shower'
 'Snow and Thunder / Windy' 'Light Sleet / Windy' 'Smoke / Windy'
 'Widespread Dust / Windy' 'Light Drizzle / Windy' 'Squalls' 'Tornado'
 'Squalls / Windy' 'Hail' 'Blowing Snow Nearby' 'Partial Fog'
 'Widespread Dust' 'Sand / Windy' 'Thunder / Wintry Mix'
 'Light Freezing Rain / Windy' 'Light Snow and Sleet / Windy'
 'Heavy Rain Shower / Windy' 'Sand / Dust Whirlwinds / Windy'
 'Light Rain Shower / Windy' 'Thunder and Hail' 'Freezing Rain'
 'Heavy Sleet' 'Sleet' 'Freezing Drizzle' 'Snow and Sleet / Windy'
 'Heavy Freezing Drizzle' 'Heavy Freezing Rain' 'Blowing Sand'
 'Thunder / Wintry Mix / Windy' 'Sleet / Windy' 'Patches of Fog / Windy'
 'Sand / Dust Whirls Nearby' 'Heavy Rain Shower' 'Drifting Snow'
 'Heavy Blowing Snow' 'Low Drifting Snow' 'Light Blowing Snow'
 'Heavy Thunderstorms with Small Hail' 'Heavy Snow with Thunder'
 'Thunder and Hail / Windy']

118

In [24]:
i = 1
variable = []

for x in df.Weather_Condition.unique():
    variable.append(i)
    i += 1
    
print(variable)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118]

In [25]:
df['Weather_Condition'] = df['Weather_Condition'].replace(df.Weather_Condition.unique(), variable)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_33004\168226722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Weather_Condition'] = df['Weather_Condition'].replace(df.Weather_Condition.unique(), variable)

In [26]:
print(df.Wind_Direction.unique())
len(df.Wind_Direction.unique())

['SW' 'WSW' 'WNW' 'West' 'NNW' 'South' 'W' 'NW' 'North' 'SSE' 'SSW' 'ESE'
 'SE' 'East' 'Variable' 'NNE' 'NE' 'ENE' 'CALM' 'S' 'VAR' 'N' 'E']

23

In [27]:
j = 1
countWindDirection = []

for x in df.Wind_Direction.unique():
    countWindDirection.append(j)
    j += 1
    
print(countWindDirection)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [28]:
df['Wind_Direction'] = df['Wind_Direction'].replace(df.Wind_Direction.unique(), countWindDirection)
df

C:\Users\Ivan\AppData\Local\Temp\ipykernel_33004\1984036252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Wind_Direction'] = df['Wind_Direction'].replace(df.Wind_Direction.unique(), countWindDirection)

,Severity,Start_Time,Distance(mi),Street,City,County,State,Zipcode,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Weather_Condition
0,3,1.454892,3.230,Outerbelt E,Dublin,Franklin,OH,43017,42.1,36.1,58.0,29.76,10.0,1,10.4,1
4,3,1.454918,0.500,I-75 S,Cincinnati,Hamilton,OH,45217,37.0,29.8,93.0,29.69,10.0,2,10.4,1
5,2,1.454919,1.427,State Route 32,Williamsburg,Clermont,OH,45176,35.6,29.2,100.0,29.66,10.0,2,8.1,2
7,2,1.454932,0.521,I-71 S,Cleveland,Cuyahoga,OH,44130,33.1,30.0,92.0,29.63,0.5,1,3.5,3
8,2,1.454941,0.491,E Hanthorn Rd,Lima,Allen,OH,45806,39.0,31.8,70.0,29.59,10.0,3,11.5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2845337,2,1.566583,0.543,Pomona Fwy E,Riverside,Riverside,CA,92501,86.0,86.0,40.0,28.92,10.0,7,13.0,14
2845338,2,1.566587,0.338,I-8 W,San Diego,San Diego,CA,92108,70.0,70.0,73.0,29.39,10.0,1,6.0,14
2845339,2,1.566587,0.561,Garden Grove Fwy,Orange,Orange,CA,92866,73.0,73.0,64.0,29.74,10.0,11,10.0,9
2845340,2,1.566587,0.772,San Diego Fwy S,Culver City,Los Angeles,CA,90230,71.0,71.0,81.0,29.62,10.0,1,8.0,14
2845341,2,1.566586,0.537,CA-210 W,Highland,San Bernardino,CA,92346,79.0,79.0,47.0,28.63,7.0,1,7.0,14